### ISSUE TITLE
Limit not working properly?

### ISSUE THREAD

**Issue by dtasada** [mcdallas/gert#12]
This looks like an awesome project! I'm gonna use it for wallpaper scraping and stuff.

Maybe I'm doing something wrong, but whenever I use the -l flag and add any kind of limit, it always limits it to 15 pictures. If I don't use any kind of limit, it downloads 43 images rather than the 25 that should be the default.

**Comment by mcdallas** [comment]
Can you share the command you are using so I can try to debug? In general it’s 25 posts per subreddit by default but some of them might not contain scrapeable media so the upper limit is 25 * number_of_subreddits but in practice it’s usually less images

**Comment by dtasada** [comment]
I've been using `gert -s WidescreenWallpaper -m 3440 -l 1 -H -o ~/walls/` (thanks for responding so fast btw lol).

**Comment by dtasada** [comment]
oh actually it might be an issue, that the first post in the 'hot' feed of this subreddit is a cluster of 15 images. it probably goes over the limit and grabs the entire post, despite the `-l 1` limit.

**Comment by dtasada** [comment]
yup that seems to be it. i switched to the 'top of all time' branch and it only downloaded one! sorry for a bit of a false alarm, but also it might be an interesting bug to investigate.

**Comment by mcdallas** [comment]
that’s the intented use, `-l` is the number of posts to scrape that might or might not contain 1 or multiple images and it will download everything from that post(s)
