### ISSUE TITLE
Downloading from Redgifs is currently not working

### ISSUE THREAD

**Issue by rareromfish** [mcdallas/gert#16]
Downloading from redgifs is currently broken, as redgifs requires api authorization for all requests. Adding support for this would be appreciated. 

https://github.com/Redgifs/api/wiki/API-access

**Comment by mcdallas** [comment]
Yes gert is using guest tokens for a while now. How is it broken exactly? I just tested and it works fine

**Comment by rareromfish** [comment]
I got errors like this `[2024-05-14T21:00:54Z ERROR gert::download] Error parsing Redgif API response from [url]` and got significantly fewer (around an order of magnitude) files back then I (wrongly, as it turns out) expected. I saw the api change happened a few months ago and made some assumptions. gert is working completely fine, I just didn't investigate enough. Sorry for wasting your time.

**Comment by Liam19** [comment]
I just tried to download from RedGifs and got the same error (Error parsing Redgif API response from [url]). Following the url lead me to this:
`{
  "error": {
    "code": "AuthorizationHeaderMissing",
    "description": "Authorization header is missing."
  }
}`

I've tried a few different redgif links and got the same thing

**Comment by mcdallas** [comment]
@Liam19 This should be fixed now if you compile from the latest master branch
