### ISSUE TITLE
Rate limit/env auth issues?

### ISSUE THREAD

**Issue by rareromfish** [mcdallas/gert#6]
I'm having some problems getting this program to work (using 0.2.2, since I'm on windows). When I run a bunch of jobs without using the .env auth file, I eventually get this error: `[2023-09-09T07:48:18Z INFO  gert] Starting data gathering from Reddit. This might take some time. Hold on....
thread 'main' panicked at 'Failed to parse JSON: reqwest::Error { kind: Decode, source: Error("missing field `kind`", line: 1, column: 46) }', src/subreddit.rs:40:93
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace` I'm assuming this is some kind of rate limiting, although it shouldn't be making that many requests (roughly 100 subs, top 10 of each). The error happens about half way through.

When I try to use my env file, I get this error: `Error: ReqwestError(reqwest::Error { kind: Decode, source: Error("missing field `access_token`", line: 1, column: 26) })` I have double and triple checked that my gert.env file has all the correct information from the template provided. Any help would be greatly appreciated.

**Comment by mcdallas** [comment]
hey @rareromfish,

For the auth issue it might be that the username/password has some special char that needs to be escaped. Similar issue here with a dollar sign in the password https://github.com/manojkarthick/reddsaver/issues/44

For the first issue, if it's not a rate limit, I would try to run with the env var `RUST_LOG=debug` to try to get the url of the post that is failing and try to debug further from there. It seems like the `kind` field is missing from the json response for some reason.

**Comment by rareromfish** [comment]
My password did have special characters in it, I changed my password (and the env file) to just numbers and letters and I still have the same error. I double checked the client ID/secret as well, they appear to be correct.

I tried using a env file with only that flag, I get this error `Error: EnvVarNotPresent(NotPresent)`. It doesn't seem to be any specific post that causes the problem I mentioned above, after running through around 50 subs the last 50 will all error out. I will try adding some delay between subreddits to see if that can fix that issue, but I would still prefer to use auth.

Thank you for your help.

**Comment by mcdallas** [comment]
Ok I just tried on windows and I think I know what the issue is. The username in the env file is overwritten by the "USERNAME" env var in windows and the authentication fails. You can confirm if that's the case with `gert -e gert.env --debug <some url>` This command should print the parsed username among other things.

If that's the case you can temporarily overwrite $USERNAME in powershell with the command `$Env:USERNAME = "my_reddit_username"` until I fix it.

**Comment by rareromfish** [comment]
It is printing my windows username, not my reddit one. I tried that powershell command and restarted my computer, it still prints my computer username. I will just wait for a fix, if you plan on fixing it. Thank you again.

**Comment by mcdallas** [comment]
You have to run the command and run gert afterwards in the same terminal session not restart in between

**Comment by mcdallas** [comment]
@rareromfish I just released v0.2.4 which should fix your issue

**Comment by rareromfish** [comment]
It does fix my auth issue, thank you.
