### ISSUE TITLE
Redgif downloads do not have sound

### ISSUE THREAD

**Issue by rareromfish** [mcdallas/gert#9]
Unsure if this effects other hosts or not, but redgif videos do not have sound for me. They are being converted to mp4s with ffmpeg, unsure how they would lose sound from the gifs however. It looks like redgif now defaults to muted when watching in a browser, perhaps there was some api change as well? A fix would be greatly appreciated.

**Comment by mcdallas** [comment]
@rareromfish can you try the new `v0.2.5`?

**Comment by rareromfish** [comment]
Regif videos work now, thank you.
